-- vim.cmd([["
--   -- hi NvimTreeIndentMarker guifg=#3c3836
--   -- hi NvimTreeFolderIcon guifg=#7c6f64
--   --
--   -- hi NvimTreeFolderName guifg=#fff
--   -- hi NvimTreeOpenedFolderName guifg=#fff
--   -- hi NvimTreeIndentMarker guifg=#282c34
-- "]])
